import type { Content } from '../types/content';

export const CONTENTS: Content[] = [
  // ─── 하동 (regionId: 'hadong') ────────────────────────────────────────
  {
    id: 'hadong-1',
    regionId: 'hadong',
    name: '화개장터',
    category: 'market',
    tagline: '섬진강변의 오랜 전통시장, 재첩국과 벚꽃길이 유명해요',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#4CAF50',
  },
  {
    id: 'hadong-2',
    regionId: 'hadong',
    name: '최참판댁',
    category: 'culture',
    tagline: '토지 소설의 배경이 된 대저택, 드라마 세트장으로도 유명해요',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#795548',
  },
  {
    id: 'hadong-3',
    regionId: 'hadong',
    name: '하동 야생차 체험관',
    category: 'experience',
    tagline: '하동 녹차의 고장에서 직접 차를 덖고 마시는 체험',
    duration: '2~3시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: true,
    color: '#388E3C',
  },
  {
    id: 'hadong-4',
    regionId: 'hadong',
    name: '섬진강 자연관찰로',
    category: 'nature',
    tagline: '섬진강을 따라 걷는 평탄한 산책로, 봄 벚꽃이 절경이에요',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#03A9F4',
  },
  {
    id: 'hadong-5',
    regionId: 'hadong',
    name: '하동 재첩 한정식',
    category: 'food',
    tagline: '섬진강 재첩으로 만든 하동 대표 향토 음식',
    duration: '1시간',
    parking: false,
    kidsRecommended: false,
    seniorsRecommended: true,
    indoor: true,
    color: '#FF8F00',
  },

  // ─── 영주 (regionId: 'yeongju') ───────────────────────────────────────
  {
    id: 'yeongju-1',
    regionId: 'yeongju',
    name: '부석사',
    category: 'culture',
    tagline: '유네스코 세계유산, 한국에서 가장 아름다운 사찰 중 하나예요',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#FF7043',
  },
  {
    id: 'yeongju-2',
    regionId: 'yeongju',
    name: '소수서원',
    category: 'culture',
    tagline: '조선 최초의 서원, 선비 문화의 발상지를 걸어봐요',
    duration: '1시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#8D6E63',
  },
  {
    id: 'yeongju-3',
    regionId: 'yeongju',
    name: '선비촌',
    category: 'experience',
    tagline: '전통 한옥마을에서 선비 생활 체험과 전통 공예를 즐겨요',
    duration: '2~3시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#5C6BC0',
  },
  {
    id: 'yeongju-4',
    regionId: 'yeongju',
    name: '무섬마을',
    category: 'nature',
    tagline: '물 위에 뜬 섬처럼 강이 마을을 감싸 안은 비경',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#26C6DA',
  },
  {
    id: 'yeongju-5',
    regionId: 'yeongju',
    name: '영주 한우 구이',
    category: 'food',
    tagline: '청정 자연에서 자란 영주 한우, 특유의 마블링이 일품이에요',
    duration: '1시간',
    parking: true,
    kidsRecommended: false,
    seniorsRecommended: true,
    indoor: true,
    color: '#EF5350',
  },

  // ─── 예천 (regionId: 'yecheon') ───────────────────────────────────────
  {
    id: 'yecheon-1',
    regionId: 'yecheon',
    name: '회룡포',
    category: 'nature',
    tagline: '강이 마을을 360도로 감싸는 예천의 가장 아름다운 경관',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: false,
    indoor: false,
    color: '#42A5F5',
  },
  {
    id: 'yecheon-2',
    regionId: 'yecheon',
    name: '삼강주막',
    category: 'culture',
    tagline: '100년 역사의 전통 주막, 막걸리 한 잔과 함께 옛 정취를 느껴요',
    duration: '30분~1시간',
    parking: true,
    kidsRecommended: false,
    seniorsRecommended: true,
    indoor: true,
    color: '#A1887F',
  },
  {
    id: 'yecheon-3',
    regionId: 'yecheon',
    name: '예천 활 체험장',
    category: 'experience',
    tagline: '전국 유일 활의 고장 예천에서 전통 국궁을 직접 체험해봐요',
    duration: '1~2시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: false,
    indoor: false,
    color: '#66BB6A',
  },
  {
    id: 'yecheon-4',
    regionId: 'yecheon',
    name: '초간정',
    category: 'nature',
    tagline: '기암괴석과 맑은 계곡 위에 자리한 아름다운 정자',
    duration: '30분~1시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: false,
    color: '#26A69A',
  },
  {
    id: 'yecheon-5',
    regionId: 'yecheon',
    name: '예천 한우불고기',
    category: 'food',
    tagline: '예천 청정 한우로 만든 달콤한 양념 불고기',
    duration: '1시간',
    parking: true,
    kidsRecommended: true,
    seniorsRecommended: true,
    indoor: true,
    color: '#FFA726',
  },
];
